---
name: Preprod release

on:
  push:
    branches:
      - preprod

jobs:
  deploy:
    runs-on: self-hosted # Le runs-on ici est le label du runner du server concerné

    steps:
      - run: ls -al
      
