---
name: Preprod release

on:
  push:
    branches:
      - preprod

jobs:
  deploy:
    runs-on: self-hosted # Le runs-on ici est le label du runner du server concerné

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # ==> sparse-checkout permet de cloner uniquement la partie souhaité du dépot (ici index.html)
          sparse-checkout: |
              index.html
          sparse-checkout-cone-mode: false

      - run: ls -alh
      
      
