name: Test Trigger

on:
  push:
    tags:
      - 'v*'  # Déclenche pour tout tag commençant par 'v'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print tag name
        run: echo "Tag pushed ${{ github.ref }}"